language: cpp
compiler: gcc
 
matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
 
    - os: linux
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-4.7
      env:
        - MATRIX_EVAL="CC=gcc-4.7 && CXX=g++-4.7"
 
    - os: linux
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
 
before_install:
   - eval "${MATRIX_EVAL}"
 
script: g++ -Ofast -Wall -Werror -std=c++11 -o ./fscr *.cpp